version: '3.7'
services:
  api-gateway:
    image: sks999us/sks-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
     - "8765:8765"
    networks:
     - currency-network
    depends_on: 
     - naming-server
     - currency-exchange
     - currency-conversion    
    environment:
     EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
#     SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
     MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
  currency-conversion:
    image: sks999us/sks-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
     - "8100:8100"
    networks:
     - currency-network
    depends_on: 
     - naming-server
     - currency-exchange     
    environment:
     EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
#     SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
     MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
  currency-exchange:
    image: sks999us/sks-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
     - "8000:8000"
    networks:
     - currency-network
    depends_on: 
     - naming-server
    environment:
     EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
#     SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
     MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
  naming-server:
    image: sks999us/sks-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
     - "8761:8761"
    networks:
     - currency-network
  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    restart: always #Restart if there is a problem starting up   
networks:
  currency-network: